name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      vault:
        image: hashicorp/vault:1.15
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
        options: >-
          --health-cmd="wget -qO- http://127.0.0.1:8200/v1/sys/health || exit 1"
          --health-interval=2s
          --health-start-period=3s
          --health-retries=20
        command: >
          vault server
          -dev
          -dev-root-token-id=root
          -dev-listen-address=0.0.0.0:8200
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Vault environment
        run: |
          echo "VAULT_ADDR=http://127.0.0.1:8200" >> $GITHUB_ENV
          echo "VAULT_TOKEN=root" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit

      - name: Dependency vulnerability scan
        run: pip-audit --strict
